In [1]:
from cs336_basics.nn import Linear, Embedding

In [17]:
torch.empty((2,))

tensor([11879.0713,     0.0000])

In [4]:
import torch
d_k = 10
theta = 10.0
x = 1.0 / (theta ** (torch.arange(0, d_k, 2)[:d_k//2].float() / d_k))
x.shape

torch.Size([5])

In [29]:
x = torch.ones(2,4)
dim = -1
exp = torch.exp(x)
exp/torch.sum(exp, dim=dim, keepdim=True)==torch.nn.functional.softmax(x, dim=dim)

tensor([[True, True, True, True],
        [True, True, True, True]])

In [3]:
import torch
x = torch.eye(5)
torch.split(x, [2,3], dim=-1)

(tensor([[1., 0.],
         [0., 1.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

In [ ]:
from cs336_basics.nn.attention import MultiheadSelfAttention
m = MultiheadSelfAttention(d_model=10, num_heads=2)
m.state_dict().keys()

odict_keys(['qkv_proj.w', 'out_proj.w'])

In [16]:
import torch
mask = torch.tril(torch.ones(3,3, dtype = torch.bool), diagonal=0)
mask

tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])

In [17]:
attn = torch.ones(3,3)
attn.masked_fill_(~mask, float('-inf'))

tensor([[1., -inf, -inf],
        [1., 1., -inf],
        [1., 1., 1.]])

In [19]:
from cs336_basics.nn.attention import MultiheadSelfAttention
m = MultiheadSelfAttention(d_model=10, num_heads=2)
for x, val in m.state_dict().items():
    print(x, val.shape)

qkv_proj.w torch.Size([30, 10])
out_proj.w torch.Size([10, 10])


In [27]:
from einops import rearrange
w = torch.Tensor([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]])
w

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.]])

In [30]:
x = rearrange(w, "... seq_len (num_heads d) -> ... num_heads seq_len d", num_heads=2)
print(x)
torch.split(x, [1,2], dim=-1)


tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.],
         [13., 14., 15.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.],
         [16., 17., 18.]]])


(tensor([[[ 1.],
          [ 7.],
          [13.]],
 
         [[ 4.],
          [10.],
          [16.]]]),
 tensor([[[ 2.,  3.],
          [ 8.,  9.],
          [14., 15.]],
 
         [[ 5.,  6.],
          [11., 12.],
          [17., 18.]]]))

In [ ]:
w = torch.ones((2, 10))
o = torch.randn((10, 10))
m.load_state_dict({'qkv_proj.w': w, 'out_proj.w': o})

<All keys matched successfully>

In [8]:
for x in m.state_dict().values():
    print(x.shape)

torch.Size([30, 10])
torch.Size([10, 10])


In [21]:
from einops import rearrange, einsum
x = torch.eye(6)
print(x)
#divide the last dimension into two halves
rearrange(x, '... (h w) -> ... h w', w=2)


tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])


tensor([[[1., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 1.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 1.]]])

In [5]:
import torch
w = torch.ones((2,3,5))
w.shape

torch.Size([2, 3, 5])

In [22]:
from cs336_basics.nn.activations import SiLU, SwiGLU

In [24]:
m = SwiGLU(in_features=5)
m.state_dict().keys()

odict_keys(['linear1.w', 'linear2.w', 'linear3.w'])

In [11]:
l = Linear(in_features=5, out_features=7, bias=True)
l.b.shape

torch.Size([7])

In [6]:
m.load_state_dict({'w': w})

<All keys matched successfully>

In [7]:
m.state_dict()

OrderedDict([('w',
              tensor([[1., 2., 3.],
                      [4., 5., 6.]]))])