In [1]:
from cs336_basics.nn import Linear, Embedding

In [17]:
torch.empty((2,))

tensor([11879.0713,     0.0000])

In [4]:
import torch
d_k = 10
theta = 10.0
x = 1.0 / (theta ** (torch.arange(0, d_k, 2)[:d_k//2].float() / d_k))
x.shape

torch.Size([5])

In [21]:
from einops import rearrange, einsum
x = torch.eye(6)
print(x)
#divide the last dimension into two halves
rearrange(x, '... (h w) -> ... h w', w=2)


tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])


tensor([[[1., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [1., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 1.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [1., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 1.]]])

In [5]:
import torch
w = torch.ones((2,3,5))
w.shape

torch.Size([2, 3, 5])

In [22]:
from cs336_basics.nn.activations import SiLU, SwiGLU

In [24]:
m = SwiGLU(in_features=5)
m.state_dict().keys()

odict_keys(['linear1.w', 'linear2.w', 'linear3.w'])

In [11]:
l = Linear(in_features=5, out_features=7, bias=True)
l.b.shape

torch.Size([7])

In [6]:
m.load_state_dict({'w': w})

<All keys matched successfully>

In [7]:
m.state_dict()

OrderedDict([('w',
              tensor([[1., 2., 3.],
                      [4., 5., 6.]]))])